// CppGenerator.cs — generates C++ glue code from parsed API type info.
// Mirrors FlaxEngine's BindingsGenerator.Cpp.cs approach.
//
// For each API_CLASS generates:
//   - DEFINE_INTERNAL_CALL stubs  (C# → C++ forward calls)
//   - _ManagedVTable struct + SetManagedVTable export  (C# → C++ registration)
//   - _CallBase stubs for virtual methods  (C# can call C++ base implementation)
//
// Usage: CppGenerator.Generate()       → .Bindings.Gen.cpp
//        CppGenerator.GenerateHeader() → .Bindings.Gen.h

using System.Text;

namespace JzRE.Build.Bindings;

public class CppGenerator
{
    private readonly ModuleInfo _module;

    public CppGenerator(ModuleInfo module) => _module = module;

    // ── .Gen.cpp ──────────────────────────────────────────────────────────────

    public string Generate()
    {
        var sb   = new StringBuilder();
        bool any = false;

        sb.AppendLine("// Auto-generated by JzRE.Build — do not edit manually.");
        sb.AppendLine($"// Module: {_module.Name}");
        sb.AppendLine();
        sb.AppendLine("#include \"InternalCalls.h\"");
        sb.AppendLine("#include \"Object.h\"");

        foreach (var file in _module.Files)
            sb.AppendLine($"#include \"{RelHeader(file.Path)}\"");

        sb.AppendLine();

        // Forward calls (C# → C++)
        sb.AppendLine("// ── Internal call stubs (C# → C++) ─────────────────────────────────────────");
        sb.AppendLine();
        foreach (var cls in _module.AllClasses)
        {
            foreach (var m in cls.Methods)
            {
                EmitInternalCall(sb, cls, m);
                any = true;
            }
        }

        // Managed vtable infrastructure (virtual dispatch C++ ← C#)
        foreach (var cls in _module.AllClasses)
        {
            var virtuals = cls.Methods.Where(m => m.IsVirtual).ToList();
            if (virtuals.Count == 0) continue;

            sb.AppendLine($"// ── Managed vtable: {cls.Name} (C# override support) ──────────────────────────");
            sb.AppendLine();
            EmitManagedVTable(sb, cls, virtuals);
            any = true;
        }

        // Managed peer factory (native → managed peer creation)
        foreach (var cls in _module.AllClasses)
        {
            if (!cls.NeedsManagedPeer) continue;

            sb.AppendLine($"// ── Managed peer factory: {cls.Name} (native creates managed wrapper) ────────");
            sb.AppendLine();
            EmitManagedPeerFactory(sb, cls);
            any = true;
        }

        if (!any)
            sb.AppendLine("// No API-annotated types found in this module.");

        return sb.ToString();
    }

    // ── .Gen.h ────────────────────────────────────────────────────────────────

    public string GenerateHeader()
    {
        var sb   = new StringBuilder();
        bool any = false;

        sb.AppendLine("// Auto-generated by JzRE.Build — do not edit manually.");
        sb.AppendLine($"// Module: {_module.Name}");
        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.AppendLine("#include \"Platform.h\"");
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine();
        sb.AppendLine("// ── Internal call declarations ──────────────────────────────────────────────");
        sb.AppendLine();

        foreach (var cls in _module.AllClasses)
        {
            foreach (var m in cls.Methods)
            {
                var self  = m.IsStatic ? "" : "void* __self";
                var plist = JoinParams(self, m.Parameters);
                sb.AppendLine($"extern \"C\" JzRE_EXPORT {CppT(m.ReturnType)} {m.InternalCallName}({plist});");
                any = true;
            }

            var virtuals = cls.Methods.Where(m => m.IsVirtual).ToList();
            if (virtuals.Count == 0 && !cls.NeedsManagedPeer) continue;

            // _CallBase declarations
            foreach (var v in virtuals)
            {
                sb.AppendLine($"extern \"C\" JzRE_EXPORT {CppT(v.ReturnType)} {v.InternalCallName}_CallBase({JoinParams("void* __self", v.Parameters)});");
            }

            // SetManagedVTable declaration
            if (virtuals.Count > 0)
            {
                foreach (var v in virtuals)
                    sb.AppendLine($"typedef {CppT(v.ReturnType)} (*{cls.Name}_{v.Name}_Fn)({JoinParams("void* __self", v.Parameters)});");

                var fnArgs = string.Join(", ", virtuals.Select(v => $"{cls.Name}_{v.Name}_Fn {v.Name}_fn"));
                sb.AppendLine($"extern \"C\" JzRE_EXPORT void {cls.Name}_SetManagedVTable({fnArgs});");
                sb.AppendLine();
            }

            // Managed peer factory declarations
            if (cls.NeedsManagedPeer)
            {
                sb.AppendLine($"typedef void* (*{cls.Name}_CreateManagedPeer_Fn)(void* nativePtr, uint32_t objectId);");
                sb.AppendLine($"extern \"C\" JzRE_EXPORT void* {cls.Name}_CreateManagedPeer(void* nativePtr, uint32_t objectId);");
                sb.AppendLine($"extern \"C\" JzRE_EXPORT void {cls.Name}_SetManagedPeerFactory({cls.Name}_CreateManagedPeer_Fn fn);");
                sb.AppendLine();
            }
        }

        if (!any)
            sb.AppendLine("// No API-annotated types found in this module.");

        return sb.ToString();
    }

    // ── Internal call stub ────────────────────────────────────────────────────

    private static void EmitInternalCall(StringBuilder sb, ClassInfo cls, FunctionInfo m)
    {
        var self  = m.IsStatic ? "" : "void* __self";
        var plist = JoinParams(self, m.Parameters);
        var args  = string.Join(", ", m.Parameters.Select(p => p.Name));
        var ret   = m.ReturnType != "void";
        var def   = DefaultLiteral(m.ReturnType);

        sb.AppendLine($"// {cls.Name}::{m.Name}");
        sb.AppendLine($"DEFINE_INTERNAL_CALL({CppT(m.ReturnType)}) {m.InternalCallName}({plist})");
        sb.AppendLine("{");

        if (!m.IsStatic)
        {
            if (ret)
            {
                sb.AppendLine($"    INTERNAL_CALL_CHECK_RETURN(__self, {def});");
                sb.AppendLine($"    auto* _obj = static_cast<{cls.Name}*>(__self);");
                sb.AppendLine($"    INTERNAL_CALL_CHECK_RETURN(_obj, {def});");
            }
            else
            {
                sb.AppendLine($"    INTERNAL_CALL_CHECK(__self);");
                sb.AppendLine($"    auto* _obj = static_cast<{cls.Name}*>(__self);");
            }
        }

        var inst = m.IsStatic ? $"{cls.Name}::" : "_obj->";
        if (ret)
        {
            sb.AppendLine($"    auto _r = {inst}{m.Name}({args});");
            sb.AppendLine("    return _r;");
        }
        else
        {
            sb.AppendLine($"    {inst}{m.Name}({args});");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Managed vtable ────────────────────────────────────────────────────────

    private static void EmitManagedVTable(StringBuilder sb, ClassInfo cls, List<FunctionInfo> virtuals)
    {
        // Function pointer typedefs
        foreach (var v in virtuals)
            sb.AppendLine($"typedef {CppT(v.ReturnType)} (*{cls.Name}_{v.Name}_Fn)({JoinParams("void* __self", v.Parameters)});");
        sb.AppendLine();

        // Vtable struct
        sb.AppendLine($"struct {cls.Name}_ManagedVTable {{");
        foreach (var v in virtuals)
            sb.AppendLine($"    {cls.Name}_{v.Name}_Fn {v.Name} = nullptr;");
        sb.AppendLine("};");
        sb.AppendLine();

        // Static vtable instance
        sb.AppendLine($"static {cls.Name}_ManagedVTable s_{cls.Name}_VTable;");
        sb.AppendLine();

        // SetManagedVTable — called from C# static constructor to register function pointers.
        // After registration, C++ code that checks the vtable can dispatch to managed overrides.
        var fnParams = string.Join(", ", virtuals.Select(v => $"{cls.Name}_{v.Name}_Fn {v.Name}_fn"));
        sb.AppendLine($"DEFINE_INTERNAL_CALL(void) {cls.Name}_SetManagedVTable({fnParams})");
        sb.AppendLine("{");
        foreach (var v in virtuals)
            sb.AppendLine($"    s_{cls.Name}_VTable.{v.Name} = {v.Name}_fn;");
        sb.AppendLine("}");
        sb.AppendLine();

        // _CallBase stubs — allow C# to invoke the C++ base implementation explicitly,
        // bypassing the C++ vtable (i.e., calling Script::OnUpdate rather than the override).
        foreach (var v in virtuals)
        {
            var plist = JoinParams("void* __self", v.Parameters);
            var args  = string.Join(", ", v.Parameters.Select(p => p.Name));
            var ret   = v.ReturnType != "void";
            var def   = DefaultLiteral(v.ReturnType);

            sb.AppendLine($"// Call C++ base: {cls.Name}::{v.Name}");
            sb.AppendLine($"DEFINE_INTERNAL_CALL({CppT(v.ReturnType)}) {v.InternalCallName}_CallBase({plist})");
            sb.AppendLine("{");
            if (ret)
            {
                sb.AppendLine($"    INTERNAL_CALL_CHECK_RETURN(__self, {def});");
                sb.AppendLine($"    auto* _obj = static_cast<{cls.Name}*>(__self);");
                sb.AppendLine($"    INTERNAL_CALL_CHECK_RETURN(_obj, {def});");
                sb.AppendLine($"    return _obj->{cls.Name}::{v.Name}({args});");
            }
            else
            {
                sb.AppendLine($"    INTERNAL_CALL_CHECK(__self);");
                sb.AppendLine($"    auto* _obj = static_cast<{cls.Name}*>(__self);");
                sb.AppendLine($"    _obj->{cls.Name}::{v.Name}({args});");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    // ── Managed peer factory ───────────────────────────────────────────────────

    /// <summary>
    /// Generates a <c>_CreateManagedPeer</c> export and a <c>_SetManagedPeerFactory</c>
    /// registration point so that native code can spawn a managed wrapper on demand.
    /// Mirrors the managed-vtable registration pattern.
    /// </summary>
    private static void EmitManagedPeerFactory(StringBuilder sb, ClassInfo cls)
    {
        sb.AppendLine($"typedef void* (*{cls.Name}_CreateManagedPeer_Fn)(void* nativePtr, uint32_t objectId);");
        sb.AppendLine();
        sb.AppendLine($"static {cls.Name}_CreateManagedPeer_Fn s_{cls.Name}_PeerFactory = nullptr;");
        sb.AppendLine();

        sb.AppendLine($"DEFINE_INTERNAL_CALL(void*) {cls.Name}_CreateManagedPeer(void* nativePtr, uint32_t objectId)");
        sb.AppendLine("{");
        sb.AppendLine($"    if (s_{cls.Name}_PeerFactory)");
        sb.AppendLine($"        return s_{cls.Name}_PeerFactory(nativePtr, objectId);");
        sb.AppendLine("    return nullptr;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine($"DEFINE_INTERNAL_CALL(void) {cls.Name}_SetManagedPeerFactory({cls.Name}_CreateManagedPeer_Fn fn)");
        sb.AppendLine("{");
        sb.AppendLine($"    s_{cls.Name}_PeerFactory = fn;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private string RelHeader(string absPath)
    {
        var norm = absPath.Replace('\\', '/');
        const string marker = "Source/Runtime/";
        var idx = norm.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
        return idx >= 0 ? norm[(idx + marker.Length)..] : Path.GetFileName(absPath);
    }

    private static string JoinParams(string selfParam, List<ParameterInfo> ps)
    {
        var items = ps.Select(p => $"{CppT(p.Type)} {p.Name}");
        if (!string.IsNullOrEmpty(selfParam))
            items = new[] { selfParam }.Concat(items);
        return string.Join(", ", items);
    }

    // Named typedef for the function pointer type used in SetManagedVTable signature.
    private static string FnPtrDecl(string clsName, FunctionInfo v) =>
        $"{clsName}_{v.Name}_Fn";

    private static string CppT(string t) => t.Trim() switch
    {
        "void"           => "void",
        "bool"           => "bool",
        "int"            => "int32_t",
        "uint"           => "uint32_t",
        "long"           => "int64_t",
        "float"          => "float",
        "double"         => "double",
        "string"         => "const char*",
        "IntPtr"         => "void*",
        _ when t.TrimEnd().EndsWith('*') => t.Trim(),  // keep pointer types as-is
        _ => t.Trim()
    };

    private static string DefaultLiteral(string retType) => retType.Trim() switch
    {
        "bool"            => "false",
        "int" or "int32_t"
             or "uint32_t" => "0",
        "float"           => "0.0f",
        "double"          => "0.0",
        "void"            => "",
        _                 => "nullptr",
    };
}
