// CppGenerator.cs — generates C++ glue code from parsed API type info.
// Mirrors FlaxEngine's BindingsGenerator.Cpp.cs.
//
// For each API_CLASS generates:
//   - DEFINE_INTERNAL_CALL stubs for API_FUNCTION methods
//   - Virtual method thunks (for C# overrides of C++ virtual methods)
//   - Type registration helpers
//
// For each API_STRUCT generates:
//   - Marshalling conversion helpers

using System.Text;

namespace JzRE.Build.Bindings;

public class CppGenerator
{
    private readonly ModuleInfo _module;

    public CppGenerator(ModuleInfo module)
    {
        _module = module;
    }

    /// <summary>
    /// Generate the complete .Gen.cpp content for this module.
    /// </summary>
    public string Generate()
    {
        var sb = new StringBuilder();
        var hasCode = false;

        sb.AppendLine("// Auto-generated by JzRE.Build — do not edit manually.");
        sb.AppendLine($"// Module: {_module.Name}");
        sb.AppendLine();
        sb.AppendLine("#include \"Scripting/InternalCalls.h\"");
        sb.AppendLine("#include \"Scripting/Object.h\"");

        // Include the header for each file that has API types
        foreach (var file in _module.Files)
        {
            var relPath = file.Path;
            // Extract relative path from Source/Runtime/
            var idx = relPath.IndexOf("Source" + Path.DirectorySeparatorChar + "Runtime" + Path.DirectorySeparatorChar);
            if (idx >= 0)
            {
                relPath = relPath[(idx + "Source/Runtime/".Length)..].Replace('\\', '/');
            }
            else
            {
                relPath = Path.GetFileName(relPath);
            }
            sb.AppendLine($"#include \"{relPath}\"");
        }

        sb.AppendLine();
        sb.AppendLine("// ── Internal calls ───────────────────────────────────────────────");
        sb.AppendLine();

        foreach (var cls in _module.AllClasses)
        {
            foreach (var method in cls.Methods)
            {
                GenerateInternalCall(sb, cls, method);
                hasCode = true;
            }

            // Generate virtual method thunks for C# overrides
            foreach (var method in cls.Methods.Where(m => m.IsVirtual))
            {
                GenerateVirtualThunk(sb, cls, method);
                hasCode = true;
            }
        }

        if (!hasCode)
        {
            sb.AppendLine("// No API-annotated types found in this module.");
        }

        return sb.ToString();
    }

    // ── Internal call generation ──────────────────────────────────────────

    private void GenerateInternalCall(StringBuilder sb, ClassInfo cls, FunctionInfo method)
    {
        // Function signature
        var selfParam = method.IsStatic ? "" : "void* __self";
        var paramList = string.Join(", ",
            new[] { selfParam }.Concat(
                method.Parameters.Select(p => $"{CppType(p.Type)} {p.Name}")
            ).Where(s => s.Length > 0));

        sb.AppendLine($"// {cls.Name}::{method.Name}");
        sb.AppendLine($"DEFINE_INTERNAL_CALL({CppType(method.ReturnType)})");
        sb.AppendLine($"    {method.InternalCallName}({paramList})");
        sb.AppendLine("{");

        if (!method.IsStatic)
        {
            sb.AppendLine($"    INTERNAL_CALL_CHECK(__self);");
            sb.AppendLine($"    auto* _obj = static_cast<{cls.Name}*>(JzObject::FromManaged(__self));");
            sb.AppendLine($"    INTERNAL_CALL_CHECK(_obj);");
        }

        // Build the call expression
        var callArgs = string.Join(", ", method.Parameters.Select(p =>
        {
            // String parameters: convert from const char*
            if (p.Type == "const char*" || p.Type == "const char*")
                return $"MUtils::ToStdString({p.Name}).c_str()";
            return p.Name;
        }));

        var instance = method.IsStatic ? $"{cls.Name}::" : "_obj->";
        var hasReturn = method.ReturnType != "void";

        if (hasReturn)
        {
            sb.AppendLine($"    auto _result = {instance}{method.Name}({callArgs});");
            sb.AppendLine("    return _result;");
        }
        else
        {
            sb.AppendLine($"    {instance}{method.Name}({callArgs});");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Virtual thunk generation ──────────────────────────────────────────

    private void GenerateVirtualThunk(StringBuilder sb, ClassInfo cls, FunctionInfo method)
    {
        sb.AppendLine($"// Virtual thunk: {cls.Name}::{method.Name} (C# override support)");
        sb.AppendLine($"// When a C# Script overrides this virtual, the managed vtable");
        sb.AppendLine($"// thunk calls the managed override instead of the native base.");
        sb.AppendLine($"DEFINE_INTERNAL_CALL({CppType(method.ReturnType)})");
        sb.AppendLine($"    {method.InternalCallName}_Base(void* __self{ParamsSuffix(method)})");
        sb.AppendLine("{");
        sb.AppendLine($"    INTERNAL_CALL_CHECK(__self);");
        sb.AppendLine($"    auto* _obj = static_cast<{cls.Name}*>(JzObject::FromManaged(__self));");
        sb.AppendLine($"    INTERNAL_CALL_CHECK(_obj);");

        var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
        if (method.ReturnType != "void")
        {
            sb.AppendLine($"    return _obj->{cls.Name}::{method.Name}({callArgs});");
        }
        else
        {
            sb.AppendLine($"    _obj->{cls.Name}::{method.Name}({callArgs});");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// Generate the companion .Gen.h that declares all generated internal call
    /// functions so other translation units can include and reference them.
    /// </summary>
    public string GenerateHeader()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by JzRE.Build — do not edit manually.");
        sb.AppendLine($"// Module: {_module.Name}");
        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.AppendLine("#include \"Core/Platform.h\"");
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine();
        sb.AppendLine("// ── Generated internal call declarations ─────────────────────────────");
        sb.AppendLine();

        bool hasDecls = false;
        foreach (var cls in _module.AllClasses)
        {
            foreach (var method in cls.Methods)
            {
                var selfParam = method.IsStatic ? "" : "void* __self";
                var paramList = string.Join(", ",
                    new[] { selfParam }
                        .Concat(method.Parameters.Select(p => $"{CppType(p.Type)} {p.Name}"))
                        .Where(s => s.Length > 0));

                sb.AppendLine($"extern \"C\" JzRE_EXPORT {CppType(method.ReturnType)} {method.InternalCallName}({paramList});");
                hasDecls = true;

                if (method.IsVirtual)
                    sb.AppendLine($"extern \"C\" JzRE_EXPORT {CppType(method.ReturnType)} {method.InternalCallName}_Base(void* __self{ParamsSuffix(method)});");
            }
        }

        if (!hasDecls)
            sb.AppendLine("// No API-annotated types found in this module.");

        return sb.ToString();
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private static string CppType(string managedType)
    {
        return managedType switch
        {
            "void" => "void",
            "bool" => "bool",
            "int" => "int32_t",
            "float" => "float",
            "double" => "double",
            "string" => "const char*",
            "IntPtr" => "void*",
            _ when managedType.EndsWith('*') => "void*",
            _ => managedType
        };
    }

    private static string ParamsSuffix(FunctionInfo method)
    {
        if (method.Parameters.Count == 0) return "";
        return ", " + string.Join(", ",
            method.Parameters.Select(p => $"{CppType(p.Type)} {p.Name}"));
    }
}
