// CSharpGenerator.cs — generates C# bindings from parsed API type info.
// Mirrors FlaxEngine's BindingsGenerator.CSharp.cs.
//
// For each API_CLASS generates a partial class with:
//   - Private [LibraryImport] internal call stubs
//   - Public managed method wrappers
//   - Property getters/setters (for API_PROPERTY)
//   - Field accessors (for API_FIELD)
//
// For each API_STRUCT generates a blittable struct with [StructLayout].
// For each API_ENUM generates an enum type.

using System.Text;

namespace JzRE.Build.Bindings;

public class CSharpGenerator
{
    private readonly ModuleInfo _module;

    /// <summary>Native DLL name used in [LibraryImport] attributes.</summary>
    public string NativeLibraryName { get; set; } = "JzRE.Runtime";

    public CSharpGenerator(ModuleInfo module)
    {
        _module = module;
    }

    /// <summary>
    /// Generate the complete .Gen.cs content for this module.
    /// </summary>
    public string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by JzRE.Build — do not edit manually.");
        sb.AppendLine($"// Module: {_module.Name}");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_module.Namespace};");
        sb.AppendLine();

        foreach (var cls in _module.AllClasses)
        {
            GenerateClass(sb, cls);
        }

        foreach (var st in _module.AllStructs)
        {
            GenerateStruct(sb, st);
        }

        foreach (var file in _module.Files)
        {
            foreach (var enm in file.Enums)
            {
                GenerateEnum(sb, enm);
            }
        }

        return sb.ToString();
    }

    // ── Class generation ──────────────────────────────────────────────────

    private void GenerateClass(StringBuilder sb, ClassInfo cls)
    {
        var baseType = cls.ManagedBaseType ?? "Object";
        var ns = string.IsNullOrEmpty(cls.Namespace) ? "JzRE" : cls.Namespace;

        sb.AppendLine($"/// <summary>Managed wrapper for native {ns}::{cls.Name}.</summary>");
        sb.AppendLine($"public partial class {cls.Name} : {baseType}");
        sb.AppendLine("{");

        // Internal call stubs (private nested class)
        sb.AppendLine("    private static partial class InternalCalls");
        sb.AppendLine("    {");

        foreach (var method in cls.Methods)
        {
            GenerateLibraryImport(sb, method);
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // Property wrappers
        foreach (var prop in cls.Properties)
        {
            GenerateProperty(sb, cls, prop);
        }

        // Public method wrappers
        foreach (var method in cls.Methods)
        {
            GenerateMethodWrapper(sb, cls, method);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── LibraryImport generation ──────────────────────────────────────────

    private void GenerateLibraryImport(StringBuilder sb, FunctionInfo method)
    {
        var returnMarshal = method.ReturnType == "bool"
            ? "[return: MarshalAs(UnmanagedType.Bool)]\n        "
            : "";

        var selfParam = method.IsStatic
            ? ""
            : $"IntPtr __self{(method.Parameters.Count > 0 ? ", " : "")}";

        var paramList = selfParam + string.Join(", ",
            method.Parameters.Select(p =>
            {
                var csType = CSharpType(p.Type);
                var marshal = "";
                if (p.Type == "const char*" || p.Type == "string")
                    marshal = "[MarshalAs(UnmanagedType.LPUTF8Str)] ";
                return $"{marshal}{csType} {p.Name}";
            }));

        var libName = NativeLibraryName;
        sb.AppendLine($"        {returnMarshal}[LibraryImport(\"{libName}\", EntryPoint = \"{method.InternalCallName}\")]");
        sb.AppendLine($"        internal static partial {CSharpType(method.ReturnType)} {method.Name}({paramList});");
        sb.AppendLine();
    }

    // ── Method wrapper generation ─────────────────────────────────────────

    private void GenerateMethodWrapper(StringBuilder sb, ClassInfo cls, FunctionInfo method)
    {
        var retType = CSharpType(method.ReturnType);
        var hasReturn = method.ReturnType != "void";
        var returnKeyword = hasReturn ? "return " : "";

        var paramDecls = string.Join(", ",
            method.Parameters.Select(p => $"{CSharpType(p.Type)} {p.Name}"));

        var callArgs = method.IsStatic
            ? string.Join(", ", method.Parameters.Select(p => p.Name))
            : (method.Parameters.Count == 0
                ? "__unmanagedPtr"
                : $"__unmanagedPtr, {string.Join(", ", method.Parameters.Select(p => p.Name))}");

        var modifiers = "";
        if (method.IsVirtual) modifiers = "virtual ";
        if (method.IsStatic) modifiers += "static ";

        sb.AppendLine($"    public {modifiers}{retType} {method.Name}({paramDecls})");
        sb.AppendLine("    {");
        sb.AppendLine($"        {returnKeyword}InternalCalls.{method.Name}({callArgs});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Property generation ───────────────────────────────────────────────

    private void GenerateProperty(StringBuilder sb, ClassInfo cls, PropertyInfo prop)
    {
        var csType = CSharpType(prop.Type);
        sb.AppendLine($"    public {csType} {prop.Name}");
        sb.AppendLine("    {");
        if (prop.HasGetter)
        {
            sb.AppendLine($"        get => InternalCalls.{cls.Name}_Get{prop.Name}(__unmanagedPtr);");
        }
        if (prop.HasSetter)
        {
            sb.AppendLine($"        set => InternalCalls.{cls.Name}_Set{prop.Name}(__unmanagedPtr, value);");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Struct generation ─────────────────────────────────────────────────

    private void GenerateStruct(StringBuilder sb, StructInfo st)
    {
        sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public partial struct {st.Name}");
        sb.AppendLine("{");

        foreach (var field in st.Fields)
        {
            sb.AppendLine($"    public {CSharpType(field.Type)} {field.Name};");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Enum generation ───────────────────────────────────────────────────

    private void GenerateEnum(StringBuilder sb, EnumInfo enm)
    {
        if (enm.IsFlags)
            sb.AppendLine("[Flags]");

        sb.AppendLine($"public enum {enm.Name}");
        sb.AppendLine("{");

        foreach (var (name, value) in enm.Values)
        {
            sb.AppendLine($"    {name} = {value},");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Type mapping ──────────────────────────────────────────────────────

    private static string CSharpType(string cppType)
    {
        return cppType.Trim() switch
        {
            "void" => "void",
            "bool" => "bool",
            "int" => "int",
            "int32_t" => "int",
            "uint32_t" => "uint",
            "int64_t" => "long",
            "uint64_t" => "ulong",
            "float" => "float",
            "double" => "double",
            "const char*" => "string",
            "char*" => "string",
            "string" => "string",
            "void*" => "IntPtr",
            "IntPtr" => "IntPtr",
            _ when cppType.EndsWith('*') => "IntPtr",
            _ => cppType
        };
    }
}
