// CSharpGenerator.cs — generates C# bindings from parsed API type info.
// Mirrors FlaxEngine's BindingsGenerator.CSharp.cs approach.
//
// For each API_CLASS generates a partial class with:
//   - Private nested InternalCalls class with [LibraryImport] stubs
//   - Public method wrappers and property accessors
//   - [UnmanagedCallersOnly] managed callbacks for virtual methods (C++ → C#)
//   - Static constructor registering callbacks via SetManagedVTable
//
// For each API_STRUCT generates a blittable [StructLayout] partial struct.
// For each API_ENUM  generates an enum.
// For API_EXPORT() free functions generates a flat static partial class.
//
// String marshalling: const char* ↔ string via StringMarshalling.Utf8.
// Bool marshalling:   [MarshalAs(UnmanagedType.I1)] on each bool parameter / return.

using System.Text;

namespace JzRE.Build.Bindings;

public class CSharpGenerator
{
    private readonly ModuleInfo _module;

    public CSharpGenerator(ModuleInfo module) => _module = module;

    // ── Top-level entry ───────────────────────────────────────────────────────

    public string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by JzRE.Build — do not edit manually.");
        sb.AppendLine($"// Module: {_module.Name}");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_module.Namespace};");
        sb.AppendLine();

        foreach (var cls in _module.AllClasses)
            EmitClass(sb, cls);

        foreach (var st in _module.AllStructs)
            EmitStruct(sb, st);

        foreach (var file in _module.Files)
            foreach (var e in file.Enums)
                EmitEnum(sb, e);

        var free = _module.AllFreeFunctions.ToList();
        if (free.Count > 0)
            EmitFlatCBindings(sb, free);

        return sb.ToString();
    }

    // ── Class ─────────────────────────────────────────────────────────────────

    private void EmitClass(StringBuilder sb, ClassInfo cls)
    {
        var virtuals = cls.Methods.Where(m => m.IsVirtual).ToList();
        bool needsStaticCtor = virtuals.Count > 0 || cls.NeedsManagedPeer;

        sb.AppendLine($"/// <summary>Bindings for native {_module.Namespace}::{cls.Name}.</summary>");
        var baseDecl = cls.ManagedBaseType != null ? $" : {cls.ManagedBaseType}" : "";
        sb.AppendLine($"public partial class {cls.Name}{baseDecl}");
        sb.AppendLine("{");

        // ── nested InternalCalls ──
        sb.AppendLine("    private static partial class InternalCalls");
        sb.AppendLine("    {");

        foreach (var m in cls.Methods)
            EmitLibraryImport(sb, m, "        ");

        foreach (var v in virtuals)
            EmitCallBaseImport(sb, v, "        ");

        if (virtuals.Count > 0)
            EmitSetVTableImport(sb, cls, virtuals, "        ");

        if (cls.NeedsManagedPeer)
            EmitSetPeerFactoryImport(sb, cls, "        ");

        sb.AppendLine("    }");
        sb.AppendLine();

        // ── public method wrappers ──
        // Non-virtual methods delegate to native via InternalCalls.
        foreach (var m in cls.Methods.Where(m => !m.IsVirtual && !m.IsConstructor))
            EmitMethodWrapper(sb, cls, m);

        // Virtual methods get empty stubs here; subclasses override them.
        // The managed vtable callback (EmitManagedCallback) dispatches to
        // these instance virtuals rather than calling InternalCalls directly.
        if (virtuals.Count > 0)
        {
            sb.AppendLine("    // ── Virtual stubs (override in subclass to intercept) ──");
            sb.AppendLine();
            foreach (var v in virtuals)
                EmitVirtualStub(sb, v);
        }

        // ── virtual dispatch infrastructure ──
        if (virtuals.Count > 0)
        {
            sb.AppendLine("    // ── Managed vtable callbacks (invoked from C++ via function pointer) ──────");
            sb.AppendLine();
            foreach (var v in virtuals)
                EmitManagedCallback(sb, cls, v);
        }

        // ── managed peer factory ──
        if (cls.NeedsManagedPeer)
        {
            sb.AppendLine("    // ── Managed peer factory (invoked from C++ to create managed wrapper) ─────");
            sb.AppendLine();
            EmitManagedPeerCallback(sb, cls);
        }

        // ── static constructor ──
        if (needsStaticCtor)
            EmitStaticCtor(sb, cls, virtuals);

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── [LibraryImport] stubs ─────────────────────────────────────────────────

    private void EmitLibraryImport(StringBuilder sb, FunctionInfo m, string indent)
    {
        var lib   = _module.NativeLibraryName;
        var entry = m.InternalCallName;
        var self  = m.IsStatic ? "" : $"IntPtr __self{(m.Parameters.Count > 0 ? ", " : "")}";
        var plist = self + string.Join(", ", m.Parameters.Select(FormatImportParam));

        sb.Append($"{indent}[LibraryImport(\"{lib}\", EntryPoint = \"{entry}\"");
        if (NeedsUtf8(m)) sb.Append(", StringMarshalling = StringMarshalling.Utf8");
        sb.AppendLine(")]");

        if (m.ReturnType == "bool")
            sb.AppendLine($"{indent}[return: MarshalAs(UnmanagedType.I1)]");

        sb.AppendLine($"{indent}internal static partial {CsT(m.ReturnType)} {m.Name}({plist});");
        sb.AppendLine();
    }

    private void EmitCallBaseImport(StringBuilder sb, FunctionInfo v, string indent)
    {
        var lib   = _module.NativeLibraryName;
        var plist = JoinParams("IntPtr __self", v.Parameters);

        sb.AppendLine($"{indent}[LibraryImport(\"{lib}\", EntryPoint = \"{v.InternalCallName}_CallBase\")]");
        sb.AppendLine($"{indent}internal static partial {CsT(v.ReturnType)} {v.Name}_CallBase({plist});");
        sb.AppendLine();
    }

    private void EmitSetVTableImport(StringBuilder sb, ClassInfo cls, List<FunctionInfo> virtuals, string indent)
    {
        var lib   = _module.NativeLibraryName;
        var parms = string.Join(", ", virtuals.Select(v => $"IntPtr {v.Name}_fn"));

        sb.AppendLine($"{indent}[LibraryImport(\"{lib}\", EntryPoint = \"{cls.Name}_SetManagedVTable\")]");
        sb.AppendLine($"{indent}internal static partial void SetManagedVTable({parms});");
        sb.AppendLine();
    }

    private void EmitSetPeerFactoryImport(StringBuilder sb, ClassInfo cls, string indent)
    {
        var lib = _module.NativeLibraryName;
        sb.AppendLine($"{indent}[LibraryImport(\"{lib}\", EntryPoint = \"{cls.Name}_SetManagedPeerFactory\")]");
        sb.AppendLine($"{indent}internal static partial void SetManagedPeerFactory(IntPtr fn);");
        sb.AppendLine();
    }

    // ── Method wrapper ────────────────────────────────────────────────────────

    private static void EmitMethodWrapper(StringBuilder sb, ClassInfo cls, FunctionInfo m)
    {
        var ret    = CsT(m.ReturnType);
        var hasRet = m.ReturnType != "void";
        var decls  = string.Join(", ", m.Parameters.Select(FormatDeclParam));
        var args   = m.IsStatic
            ? string.Join(", ", m.Parameters.Select(p => p.Name))
            : (m.Parameters.Count == 0
                ? "__unmanagedPtr"
                : $"__unmanagedPtr, {string.Join(", ", m.Parameters.Select(p => p.Name))}");

        var mods = (m.IsStatic ? "static " : "") + (m.IsVirtual ? "virtual " : "");
        var body = hasRet
            ? $"InternalCalls.{m.Name}({args})"
            : $"InternalCalls.{m.Name}({args})";

        if (hasRet)
            sb.AppendLine($"    public {mods}{ret} {m.Name}({decls}) => {body};");
        else
            sb.AppendLine($"    public {mods}void {m.Name}({decls}) => {body};");

        sb.AppendLine();
    }

    // ── Virtual stub ──────────────────────────────────────────────────────────

    private static void EmitVirtualStub(StringBuilder sb, FunctionInfo v)
    {
        var ret    = CsT(v.ReturnType);
        var hasRet = v.ReturnType != "void";
        var decls  = string.Join(", ", v.Parameters.Select(FormatDeclParam));

        sb.AppendLine("    /// <summary>Override to intercept native → managed calls.</summary>");
        if (hasRet)
            sb.AppendLine($"    public virtual {ret} {v.Name}({decls}) => default;");
        else
            sb.AppendLine($"    public virtual void {v.Name}({decls}) {{ }}");
        sb.AppendLine();
    }

    // ── Property wrapper ──────────────────────────────────────────────────────

    private static void EmitProperty(StringBuilder sb, ClassInfo cls, PropertyInfo prop)
    {
        var t = CsT(prop.Type);
        sb.AppendLine($"    public {t} {prop.Name}");
        sb.AppendLine("    {");
        if (prop.HasGetter)
            sb.AppendLine($"        get => InternalCalls.{cls.Name}_Get{prop.Name}(__unmanagedPtr);");
        if (prop.HasSetter)
            sb.AppendLine($"        set => InternalCalls.{cls.Name}_Set{prop.Name}(__unmanagedPtr, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Managed vtable callbacks ──────────────────────────────────────────────

    private static void EmitManagedCallback(StringBuilder sb, ClassInfo cls, FunctionInfo v)
    {
        var ret    = CsT(v.ReturnType);
        var hasRet = v.ReturnType != "void";
        var plist  = "IntPtr __self" + (v.Parameters.Count > 0
            ? ", " + string.Join(", ", v.Parameters.Select(FormatDeclParam)) : "");
        var args   = string.Join(", ", v.Parameters.Select(p => p.Name));

        sb.AppendLine($"    [UnmanagedCallersOnly(CallConvs = new[] {{ typeof(CallConvCdecl) }})]");
        sb.AppendLine($"    private static {ret} ManagedCallback_{v.Name}({plist})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var _obj = Object.FromUnmanagedPtr(__self) as {cls.Name};");

        if (hasRet)
            sb.AppendLine($"        return _obj != null ? _obj.{v.Name}({args}) : default;");
        else
            sb.AppendLine($"        _obj?.{v.Name}({args});");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Managed peer factory callback ───────────────────────────────────────────

    /// <summary>
    /// Generates a <c>[UnmanagedCallersOnly]</c> callback that creates a new managed
    /// peer instance and returns its GCHandle.  Registered with the native side via
    /// <c>SetManagedPeerFactory</c> so that native code can spawn the managed wrapper
    /// on demand.
    /// </summary>
    private static void EmitManagedPeerCallback(StringBuilder sb, ClassInfo cls)
    {
        sb.AppendLine($"    [UnmanagedCallersOnly(CallConvs = new[] {{ typeof(CallConvCdecl) }})]");
        sb.AppendLine($"    private static IntPtr CreateManagedPeer(IntPtr nativePtr, uint objectId)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var obj = new {cls.Name}();");
        sb.AppendLine("        obj.SetInternalValues(nativePtr, objectId);");
        sb.AppendLine("        return GCHandle.ToIntPtr(GCHandle.Alloc(obj));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Static constructor — registers managed callbacks with the native vtable ──

    private static void EmitStaticCtor(StringBuilder sb, ClassInfo cls, List<FunctionInfo> virtuals)
    {
        sb.AppendLine($"    static {cls.Name}()");
        sb.AppendLine("    {");
        sb.AppendLine("        unsafe");
        sb.AppendLine("        {");

        if (virtuals.Count > 0)
        {
            sb.AppendLine("            InternalCalls.SetManagedVTable(");

            for (int i = 0; i < virtuals.Count; i++)
            {
                var v      = virtuals[i];
                var csRet  = CsT(v.ReturnType);
                var pTypes = string.Join(", ",
                    new[] { "IntPtr" }.Concat(v.Parameters.Select(p => CsT(p.Type))));
                var sep    = i < virtuals.Count - 1 ? "," : "";

                sb.AppendLine($"                (IntPtr)(delegate* unmanaged[Cdecl]<{pTypes}, {csRet}>)&ManagedCallback_{v.Name}{sep}");
            }

            sb.AppendLine("            );");
        }

        if (cls.NeedsManagedPeer)
        {
            if (virtuals.Count > 0) sb.AppendLine();
            sb.AppendLine("            InternalCalls.SetManagedPeerFactory(");
            sb.AppendLine("                (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, uint, IntPtr>)&CreateManagedPeer);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    // ── Struct ────────────────────────────────────────────────────────────────

    private static void EmitStruct(StringBuilder sb, StructInfo st)
    {
        sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public partial struct {st.Name}");
        sb.AppendLine("{");
        foreach (var f in st.Fields)
            sb.AppendLine($"    public {CsT(f.Type)} {f.Name};");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Enum ──────────────────────────────────────────────────────────────────

    private static void EmitEnum(StringBuilder sb, EnumInfo e)
    {
        if (e.IsFlags) sb.AppendLine("[Flags]");
        sb.AppendLine($"public enum {e.Name}");
        sb.AppendLine("{");
        foreach (var (name, val) in e.Values)
            sb.AppendLine($"    {name} = {val},");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Flat C API bindings (API_EXPORT free functions) ───────────────────────
    // Generates a static partial class with one [LibraryImport] per free function.
    // Mirrors the hand-written NativeRuntime.cs pattern so generated code can
    // eventually replace it.

    private void EmitFlatCBindings(StringBuilder sb, List<FreeFunctionInfo> fns)
    {
        var lib       = _module.NativeLibraryName;
        var className = lib.Replace(".", "").Replace("-", "") + "Native";

        sb.AppendLine($"/// <summary>P/Invoke bindings for exported C functions in {lib}.</summary>");
        sb.AppendLine($"public static partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string Lib = \"{lib}\";");
        sb.AppendLine();

        // Cross-platform DLL resolver — same pattern as the hand-written NativeRuntime.cs.
        sb.AppendLine($"    static {className}()");
        sb.AppendLine("    {");
        sb.AppendLine($"        NativeLibrary.SetDllImportResolver(typeof({className}).Assembly, (name, _, _) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            if (name != Lib) return IntPtr.Zero;");
        sb.AppendLine("            string ext = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? \".dll\"");
        sb.AppendLine("                       : RuntimeInformation.IsOSPlatform(OSPlatform.OSX)     ? \".dylib\"");
        sb.AppendLine("                       : \".so\";");
        sb.AppendLine("            return NativeLibrary.Load(Path.Combine(AppContext.BaseDirectory, name + ext));");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var fn in fns)
        {
            var retCs  = CsT(fn.ReturnType);
            var plist  = string.Join(", ", fn.Parameters.Select(FormatImportParam));
            var needsU8 = NeedsUtf8Free(fn);

            sb.Append($"    [LibraryImport(Lib, EntryPoint = \"{fn.EntryPoint}\"");
            if (needsU8) sb.Append(", StringMarshalling = StringMarshalling.Utf8");
            sb.AppendLine(")]");

            if (fn.ReturnType == "bool")
                sb.AppendLine("    [return: MarshalAs(UnmanagedType.I1)]");

            sb.AppendLine($"    public static partial {retCs} {fn.Name}({plist});");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    // Parameter as it appears in [LibraryImport] declaration (with marshal attrs).
    private static string FormatImportParam(ParameterInfo p)
    {
        var dir  = p.IsOut ? "out " : p.IsRef ? "ref " : "";
        var type = CsT(p.Type);

        if (p.Type == "bool")
            return $"[MarshalAs(UnmanagedType.I1)] {dir}bool {p.Name}";

        // string / const char* marshalling is handled at the [LibraryImport] level
        return $"{dir}{type} {p.Name}";
    }

    // Parameter as it appears in public method signatures (no marshal attrs).
    private static string FormatDeclParam(ParameterInfo p)
    {
        var dir = p.IsOut ? "out " : p.IsRef ? "ref " : "";
        return $"{dir}{CsT(p.Type)} {p.Name}";
    }

    private static string JoinParams(string selfParam, List<ParameterInfo> ps)
    {
        var items = ps.Select(FormatDeclParam);
        if (!string.IsNullOrEmpty(selfParam))
            items = new[] { selfParam }.Concat(items);
        return string.Join(", ", items);
    }

    // True when any string-typed parameter or return value is present.
    private static bool NeedsUtf8(FunctionInfo m) =>
        IsStringType(m.ReturnType) || m.Parameters.Any(p => IsStringType(p.Type));

    private static bool NeedsUtf8Free(FreeFunctionInfo fn) =>
        IsStringType(fn.ReturnType) || fn.Parameters.Any(p => IsStringType(p.Type));

    private static bool IsStringType(string t) =>
        t.Trim() is "string" or "const char*" or "char*";

    // Maps C++ types to C# types.
    // Mirrors FlaxEngine's CSharpGenerator type table.
    private static string CsT(string t) => t.Trim() switch
    {
        "void"                   => "void",
        "bool"                   => "bool",
        "int"   or "int32_t"     => "int",
        "uint"  or "uint32_t"    => "uint",
        "long"  or "int64_t"     => "long",
        "ulong" or "uint64_t"    => "ulong",
        "float"                  => "float",
        "double"                 => "double",
        "const char*" or "char*" => "string",
        "void*"                  => "IntPtr",
        "IntPtr"                 => "IntPtr",
        _ when t.TrimEnd().EndsWith('*') => "IntPtr",
        _ => t.Trim(),
    };
}
