#pragma once
#include "Object.h"
#include "API.h"

// ── Script — base class for user scripts ────────────────────────────────────
// Mirrors FlaxEngine's Script class.  User scripts (both native and managed)
// derive from this class and override lifecycle methods.
//
// C++ overrides are called directly.  C# overrides are called through the
// managed vtable thunk generated by the bindings generator (Phase 3).
//
// Usage:
//   class MyScript : public Script {
//       API_FUNCTION() void OnUpdate(float dt) override { ... }
//   };

API_CLASS()
class Script : public Object
{
public:
    Script();

    API_PROPERTY()
    bool GetEnabled() const { return _enabled; }
    void SetEnabled(bool value) { _enabled = value; }

    // ── Lifecycle methods (virtual — C# scripts override these) ──────────

    API_FUNCTION()
    virtual void OnEnable();

    API_FUNCTION()
    virtual void OnDisable();

    API_FUNCTION()
    virtual void OnUpdate(float deltaTime);

    API_FUNCTION()
    virtual void OnDestroy();

protected:
    bool _enabled = true;
};
